

@host = http://localhost:3000
@content_type = application/json


# @name create
POST {{host}}/books/ HTTP/1.1
Content-Type: {{content_type}}

{
    "title1": "sample",
    "author": "ppvan"
}
###

# @name get
GET http://localhost:3000/books/ HTTP/1.1


###

# @name get_one

@id = 659297a61283901b8cb5705d
GET {{host}}/books/{{id}}


### 


# @name update_one

@id = 659297be1283901b8cb57060
PUT {{host}}/books/{{id}}
Content-Type: {{content_type}}

{
    "titlae": "One shot 123",
    "authoar": "Aqua"
}

### 

# @name delete_one

@id = 659297a61283901b8cb5705d
DELETE {{host}}/books/{{id}}

### 